version: "3"

services:
  feapder_front:
    container_name: feapder_front
    image: boris0621/feapder_front:1.1
    restart: always
    environment:
      - BACKEND_URL=http://feapder_backend:8000
    ports:
      - 80:80 # 前端端口 （自定义端口:80）
    depends_on:
      - feapder_backend

  feapder_backend:
    container_name: feapder_backend
    image: boris0621/feapder_backend:1.2
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --workers 1 --port 8000 # workers 为后端服务的个数，爬虫多可改大点
    ports:
      - 8000:8000 # 后端端口 （自定义端口:8000）
    environment:
      - FEAPDER_BACKEND_URL=http://ip:8000 # **必填  服务端内网地址 ；端口需与自定义端口对上
      - AUTHORIZATION_CODE= # **必填  授权码
      - DB_URL=mysql+pymysql://root:root123@mysql:3306/feapder_platform?charset=utf8mb4 # 后端数据库配置
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440 # 管理系统账号cookie过期时间 单位分钟
      - SPIDER_IMAGE=boris0621/feapder:1.1 # 爬虫镜像
      - SPIDER_AUTO_PULL_IMAGE=1 # 是否自动拉取镜像 否则需要在爬虫节点手动 docker pull 爬虫镜像，为了加快启动速度，可以设置0
      - SPIDER_ENV={} # 爬虫环境变量 值为json类型
      - SPIDER_RUN_ARGS={"--network":"host","--limit-cpu":1,"--limit-memory":"1G"} # 爬虫容器启动参数，支持的参数使用 docker service create --help 查看
      # git ssh 私有密钥，不填则使用默认的
      - GIT_SSH_PRIVATE_KEY=
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/data/feapder/projects:/projects" # 上传的项目挂载， 本地目录:容器路径
    depends_on:
      - mysql

  mysql:
    container_name: feapder_backend_mysql
    command: mysqld --character-set-server=utf8mb4
    restart: always
    image: mysql:5.7.29
    ports:
      - "33306:3306"
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root123"
      - "MYSQL_DATABASE=feapder_platform"
      - "MYSQL_PASSWORD=root123"
    volumes:
      - "~/data/feapder/feapder_backend_mysql:/var/lib/mysql" # mysql 挂载， 本地目录:容器路径