version: "3"

services:
  feapder_front:
    container_name: feapder_front
    image: ${FRONT_IMAGE}
    restart: always
    environment:
      - BACKEND_URL=http://feapder_backend:${BACKEND_PORT}
      - FRONT_PORT=${FRONT_PORT}
    ports:
      - ${FRONT_PORT}:${FRONT_PORT} # 前端端口 （自定义端口:80）
    depends_on:
      - feapder_backend

  feapder_backend:
    container_name: feapder_backend
    image: ${BACKEND_IMAGE}
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --workers ${BACKEND_WORKER} --port ${BACKEND_PORT} # workers 为后端服务的个数，爬虫多可改大点
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT} # 后端端口 （自定义端口:8000）
    environment:
      - FEAPDER_BACKEND_URL=http://${BACKEND_IP}:${BACKEND_PORT} # **必填  服务端内网地址 ；端口需与自定义端口对上
      - AUTHORIZATION_CODE=${AUTHORIZATION_CODE} # **必填  授权码
      - DB_URL=mysql+pymysql://root:root123@mysql:3306/feapder_platform?charset=utf8mb4 # 后端数据库配置
      - REDIS_DB_URL=redis://@redis:6379/0 # redis数据库连接配置 redis://[[username]:[password]]@[host]:[port]/[db]
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440 # 管理系统账号cookie过期时间 单位分钟
      - SPIDER_IMAGE=${SPIDER_IMAGE} # 爬虫镜像
      - SPIDER_AUTO_PULL_IMAGE=1 # 是否自动拉取镜像 否则需要在爬虫节点手动 docker pull 爬虫镜像，为了加快启动速度，可以设置0
      - SPIDER_ENV={} # 爬虫环境变量 值为json类型
      # 爬虫容器启动参数，支持的参数使用 docker service create --help 查看
      - SPIDER_RUN_ARGS={
        "--network":"host",
        "--limit-cpu":1,
        "--limit-memory":"1G"
        }
      # git ssh 私有密钥，不填则使用默认的
      - GIT_SSH_PRIVATE_KEY=${GIT_SSH_PRIVATE_KEY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/data/feapder/projects:/projects" # 上传的项目挂载， 本地目录:容器路径
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: feapder_backend_mysql
    command: mysqld --character-set-server=utf8mb4
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/feapderd/mysql:5.7.29
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root123"
      - "MYSQL_DATABASE=feapder_platform"
      - "MYSQL_PASSWORD=root123"
    volumes:
      - "~/data/feapder/feapder_backend_mysql:/var/lib/mysql" # mysql 挂载， 本地目录:容器路径

  redis:
    container_name: feapder_backend_redis
    command: redis-server --appendonly yes
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/feapderd/redis:6.0.10
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - "~/data/feapder/feapder_backend_redis:/data" # redis 挂载， 本地目录:容器路径